

export const mockProducts = [
  {
    "title": "Chicken Biryani",
    "price": 1500,
    "imageUrl": "https://images.unsplash.com/photo-1716550781939-beb7d7247aae?auto=format&fit=crop&q=80&w=387",
    "isNew": true,
    "isFavorite": false,
    "description": "Aromatic basmati rice cooked with tender chicken and rich spices.",
    "link": "/allProds/chicken-biryani",
    "category": "Desi Tarka",
    "categorySlug": "desi-tarka",
    "categoryId": "6915f19662fa49ba156190c6"
  },
  {
    "title": "Beef Burger",
    "price": 950,
    "imageUrl": "https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&q=80&w=815",
    "isNew": false,
    "isFavorite": true,
    "description": "Juicy grilled beef patty with fresh veggies and melted cheese.",
    "link": "/allProds/beef-burger",
    "category": "Fastfood",
    "categorySlug": "fastfood",
    "categoryId": "6915ecc762fa49ba156190a5"
  },
  {
    "title": "Zinger Burger",
    "price": 1150,
    "imageUrl": "https://images.unsplash.com/photo-1513185158878-8d8c2a2a3da3?auto=format&fit=crop&q=80&w=870",
    "isNew": false,
    "isFavorite": false,
    "description": "Crispy fried chicken fillet layered with creamy mayo and lettuce.",
    "link": "/allProds/zinger-burger",
    "category": "Fastfood",
    "categorySlug": "fastfood",
    "categoryId": "6915ecc762fa49ba156190a5"
  },
  {
    "title": "Chicken Karahi",
    "price": 1950,
    "imageUrl": "https://images.unsplash.com/photo-1603496987351-f84a3ba5ec85?auto=format&fit=crop&q=80&w=876",
    "isNew": true,
    "isFavorite": false,
    "description": "Traditional Pakistani chicken curry with rich tomato gravy and spices.",
    "link": "/allProds/chicken-karahi",
    "category": "Desi Tarka",
    "categorySlug": "desi-tarka",
    "categoryId": "6915f19662fa49ba156190c6"
  },
  {
    "title": "Beef Seekh Kabab",
    "price": 1450,
    "imageUrl": "https://images.unsplash.com/photo-1603360946369-dc9bb6258143?auto=format&fit=crop&q=80&w=435",
    "isNew": false,
    "isFavorite": false,
    "description": "Smoky, spiced minced beef kababs grilled to perfection.",
    "link": "/allProds/beef-seekh-kabab",
    "category": "Starter",
    "categorySlug": "starter",
    "categoryId": "6915f19662fa49ba156190c7"
  },
  {
    "title": "Paratha Roll",
    "price": 700,
    "imageUrl": "https://images.deliveryhero.io/image/fd-pk/LH/rtz5-listing.jpg",
    "isNew": false,
    "isFavorite": false,
    "description": "Crispy paratha wrapped with spicy chicken and chutney.",
    "link": "/allProds/paratha-roll",
    "category": "Fastfood",
    "categorySlug": "fastfood",
    "categoryId": "6915ecc762fa49ba156190a5"
  },
  {
    "title": "Chicken Shawarma",
    "price": 850,
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt78xTYyBohrp1QjLu3N-7s3ZSWspVFwsH_Ddxx4s5qjxYrT_qLfY_azUAQ8Qm7A6ueLE&usqp=CAU",
    "isNew": true,
    "isFavorite": false,
    "description": "Middle Eastern wrap filled with marinated chicken and garlic sauce.",
    "link": "/allProds/chicken-shawarma",
    "category": "Fastfood",
    "categorySlug": "fastfood",
    "categoryId": "6915ecc762fa49ba156190a5"
  },
  {
    "title": "French Fries",
    "price": 500,
    "imageUrl": "https://images.unsplash.com/photo-1541592106381-b31e9677c0e5?auto=format&fit=crop&q=80&w=870",
    "isNew": false,
    "isFavorite": true,
    "description": "Crispy golden fries with a pinch of salt — the perfect snack.",
    "link": "/allProds/french-fries",
    "category": "Starter",
    "categorySlug": "starter",
    "categoryId": "6915f19662fa49ba156190c7"
  },
  {
    "title": "Chicken Tikka",
    "price": 1750,
    "imageUrl": "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/29/37/d1/24/chicken-tikka.jpg?w=900&h=500&s=1",
    "isNew": false,
    "isFavorite": false,
    "description": "Tender boneless chicken pieces grilled in spicy marinade.",
    "link": "/allProds/chicken-tikka",
    "category": "Desi Tarka",
    "categorySlug": "desi-tarka",
    "categoryId": "6915f19662fa49ba156190c6"
  },
  {
    "title": "Beef Nihari",
    "price": 1800,
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQdbnoYVebwoEh79Qh4Q-a7EQEJX75edMoK5A&s",
    "isNew": true,
    "isFavorite": false,
    "description": "Slow-cooked beef stew rich in flavor and perfect for naan pairing.",
    "link": "/allProds/beef-nihari",
    "category": "Desi Tarka",
    "categorySlug": "desi-tarka",
    "categoryId": "6915f19662fa49ba156190c6"
  },
  {
    "title": "Aloo Samosa (6 pcs)",
    "price": 650,
    "imageUrl": "https://www.cookwithnabeela.com/wp-content/uploads/2024/02/AlooSamosa3.webp",
    "isNew": false,
    "isFavorite": false,
    "description": "Crispy fried pastry stuffed with spicy potato filling.",
    "link": "/allProds/aloo-samosa",
    "category": "Starter",
    "categorySlug": "starter",
    "categoryId": "6915f19662fa49ba156190c7"
  },
  {
    "title": "Dahi Bhallay",
    "price": 750,
    "imageUrl": "https://images.deliveryhero.io/image/fd-pk/LH/qd7n-listing.jpg",
    "isNew": true,
    "isFavorite": false,
    "description": "Soft lentil balls served with yogurt and tangy chutneys.",
    "link": "/allProds/dahi-bhallay",
    "category": "Starter",
    "categorySlug": "starter",
    "categoryId": "6915f19662fa49ba156190c7"
  },
  {
    "title": "Gol Gappay (Plate)",
    "price": 600,
    "imageUrl": "https://blessmyfoodbypayal.com/wp-content/uploads/2020/04/IMG_20200415_154503_20200422004151679.jpg",
    "isNew": false,
    "isFavorite": true,
    "description": "Crispy hollow puris filled with spicy tangy water.",
    "link": "/allProds/gol-gappay",
    "category": "Starter",
    "categorySlug": "starter",
    "categoryId": "6915f19662fa49ba156190c7"
  },
  {
    "title": "Chicken Sandwich",
    "price": 700,
    "imageUrl": "https://images.unsplash.com/photo-1670710029403-607db8eeec83?auto=format&fit=crop&q=80&w=726",
    "isNew": false,
    "isFavorite": false,
    "description": "Grilled chicken sandwich with cheese, lettuce, and mayo.",
    "link": "/allProds/chicken-sandwich",
    "category": "Fastfood",
    "categorySlug": "fastfood",
    "categoryId": "6915ecc762fa49ba156190a5"
  },
  {
    "title": "Malai Boti",
    "price": 1550,
    "imageUrl": "https://i.ytimg.com/vi/iXHzzDbw_YY/maxresdefault.jpg",
    "isNew": true,
    "isFavorite": false,
    "description": "Creamy, tender chicken cubes marinated in yogurt and spices.",
    "link": "/allProds/malai-boti",
    "category": "Desi Tarka",
    "categorySlug": "desi-tarka",
    "categoryId": "6915f19662fa49ba156190c6"
  },
  {
    "title": "Chapli Kabab",
    "price": 1350,
    "imageUrl": "https://static.sooperchef.pk/topics/2023/02/beef-chapli-kabab-recipe-550x375.jpg",
    "isNew": false,
    "isFavorite": false,
    "description": "Spicy minced meat patties from the northwest frontier.",
    "link": "/allProds/chapli-kabab",
    "category": "Starter",
    "categorySlug": "starter",
    "categoryId": "6915f19662fa49ba156190c7"
  },
  {
    "title": "Chicken Haleem",
    "price": 1100,
    "imageUrl": "https://www.licious.in/blog/wp-content/uploads/2022/04/Chicken-Haleem-Cooked-min-compressed-scaled.jpg",
    "isNew": true,
    "isFavorite": true,
    "description": "Thick, savory porridge made from chicken, lentils, and wheat.",
    "link": "/allProds/chicken-haleem",
    "category": "Desi Tarka",
    "categorySlug": "desi-tarka",
    "categoryId": "6915f19662fa49ba156190c6"
  },
  {
    "title": "Loaded Fries",
    "price": 900,
    "imageUrl": "https://plus.unsplash.com/premium_photo-1673747885079-6a915d368c82?auto=format&fit=crop&q=80&w=870",
    "isNew": false,
    "isFavorite": false,
    "description": "Fries topped with cheese, chicken, and spicy sauces.",
    "link": "/allProds/loaded-fries",
    "category": "Starter",
    "categorySlug": "starter",
    "categoryId": "6915f19662fa49ba156190c7"
  },
  {
    "title": "Chicken Pakora",
    "price": 750,
    "imageUrl": "https://www.unileverfoodsolutions.pk/dam/global-ufs/mcos/meps/pakistan/calcmenu/recipes/PK-recipes/chicken-pakora-with-honey-chilli-sauce/chicken-pakora-with-honey-chilli-sauce-main-header-1260x709.jpg",
    "isNew": false,
    "isFavorite": false,
    "description": "Crispy fried chicken bites coated in chickpea flour batter.",
    "link": "/allProds/chicken-pakora",
    "category": "Starter",
    "categorySlug": "starter",
    "categoryId": "6915f19662fa49ba156190c7"
  },
  {
    "title": "Bun Kebab",
    "price": 550,
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR5ZnWOg_4PRl1i2mofz2A6idppwJ8b0d7BNFjri-q8b-tWZc-fy55WNvqh-3lfIQ3joPI&usqp=CAU",
    "isNew": true,
    "isFavorite": false,
    "description": "Spicy street-style Pakistani burger with chutney and egg.",
    "link": "/allProds/bun-kebab",
    "category": "Fastfood",
    "categorySlug": "fastfood",
    "categoryId": "6915ecc762fa49ba156190a5"
  },
  {
    "title": "BBQ Platter",
    "price": 2000,
    "imageUrl": "https://images.deliveryhero.io/image/fd-pk/LH/r623-listing.jpg",
    "isNew": false,
    "isFavorite": false,
    "description": "A mix of grilled delights — tikka, boti, kabab, and naan.",
    "link": "/allProds/bbq-platter",
    "category": "Desi Tarka",
    "categorySlug": "desi-tarka",
    "categoryId": "6915f19662fa49ba156190c6"
  },
  {
    "title": "Tandoori Naan",
    "price": 350,
    "imageUrl": "https://i0.wp.com/www.shanazrafiq.com/wp-content/uploads/2021/07/1-Tandoori-Naan-5.jpg?fit=1024%2C681&ssl=1",
    "isNew": true,
    "isFavorite": false,
    "description": "Soft, fluffy naan baked fresh in a traditional clay oven.",
    "link": "/allProds/tandoori-naan",
    "category": "Desi Tarka",
    "categorySlug": "desi-tarka",
    "categoryId": "6915f19662fa49ba156190c6"
  },
  {
    "title": "Chana Chaat",
    "price": 500,
    "imageUrl": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSJwlxDwwwQg1h1UXEX9mDPwosDL6ayhyqgMw&s",
    "isNew": false,
    "isFavorite": false,
    "description": "Spicy and tangy chickpea salad mixed with chutneys and onions.",
    "link": "/allProds/chana-chaat",
    "category": "Starter",
    "categorySlug": "starter",
    "categoryId": "6915f19662fa49ba156190c7"
  },
  {
    "title": "Falooda",
    "price": 800,
    "imageUrl": "https://www.cookwithkushi.com/wp-content/uploads/2019/06/best_falooda_ice_cream_Dessert_drink_Indian.jpg",
    "isNew": false,
    "isFavorite": false,
    "description": "Refreshing dessert drink with ice cream, rose syrup, and basil seeds.",
    "link": "/allProds/falooda",
    "category": "Dessert/Shakes",
    "categorySlug": "dessert-shakes",
    "categoryId": "6915f19662fa49ba156190c8"
  }
]