
//layout.js
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";
import MainNavbar from "./Components/Navbar/MainNavbar";
import Footer from "./Components/Footer/Footer";
import { SessionProvider } from "next-auth/react";
import { FetchProducts } from "./context/ProdContext";
import { CartProvider } from "./context/CartContext";
import { WishListProvider } from "./context/LikeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


const fetchAllProducts = async (categorySlug) => {
  const url = categorySlug
    ? `${process.env.NEXTAUTH_URL}/api/products?category=${categorySlug}`
    : `${process.env.NEXTAUTH_URL}/api/products`;

  try {
    const res = await fetch(url, { cache: "no-store", });

    if (!res.ok) return [];

    return await res.json();
  } catch (err) {
    console.error("Fetch error:", err);
    return [];
  }
}



export default async function RootLayout({ children, session }) {
  const items = await fetchAllProducts();
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SessionProvider session={session}>
          <FetchProducts items={items}>
            <CartProvider >
              <WishListProvider>
              <Navbar />
              {children}
              <Footer />

              </WishListProvider>
            </CartProvider>
          </FetchProducts>
        </SessionProvider>

      </body>
    </html>
  );
}
