import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar/Navbar";
import MainNavbar from "./Components/Navbar/MainNavbar";
import Footer from "./Components/Footer/Footer";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, session }) {
  return (
   <html lang="en" className=" dark">
      <body>
        <Providers>
          <Navbar />
          {children}
          <Footer />
          </Providers>
      </body>
    </html>
  );
}
